sudo: false
language: python
cache: pip
python:
  - 3.6
install:
  - python3 -m pip install -r requirements.txt
script:
  - git submodule update --init
  - python3 -m pelican content -vvv -o output -s pelicanconf.py

deploy:
  provider: pages
  fqdn: sanantoniodevs.com
  local-dir: output/
  target-branch: master
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: website
